### ISSUE TITLE
Upgrade ETH-xDai bridge to use the Fee Manager contract 

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge-contracts#136]
As soon as #125 fully addressed, it is necessary to develop a procedure to upgrade the existing ETH-xDai bridge contracts to use the Fee Manager contract.

The current thoughts are:
1. Upgrade the validators contract on the Home side. As part of the upgrade, initialize reward accounts (no another way except hardcoding the accounts) for the corresponding validators.
2. Deploy the Fee Manager contract on the Home side.
3. Upgrade the bridge account on the Home side. As part of the upgrade, set the Fee Manager address and define a fee part.

Provide very detailed step by step instructions for the bridge validators to perform the upgrade. The instructions must specify bytes sequences that needs to be used by the multisig contract to initiate and finish the upgrade.

**Comment by akolotov** [comment]
@patitonar Have we prepared a version of contracts for the xDai bridge to upgrade the bridge after the FeeManager introduction? I found only [one](https://gist.github.com/patitonar/88e6d2a6b2253056ace9ec662b7465f6) HomeBridge contract implementation that was planned for upgrade but it was for the issue with 0 tokens transfers. Do you have links for other implementations?

**Comment by patitonar** [comment]
I found the same as you, only the implementation for 0 tokens transfers. I don't think we prepared a version of contract to upgrade xDai bridge for the introduction of FeeManager

**Comment by akolotov** [comment]
The upgrade was successfully performed in December, 2019: https://forum.poa.network/t/migration-of-the-xdai-tokenbridge-completed/3212
