### ISSUE TITLE
Document functions and events in the contracts

### ISSUE THREAD

**Issue by varasev** [poanetwork/tokenbridge-contracts#320]
Let’s add `@dev` comments for all functions in the bridge contracts because there are many features and it’s often hard for a code reader to understand what some function/event is needed for. Just short comments describing each function and event like it is done for POSDAO contracts, e.g.: https://github.com/poanetwork/posdao-contracts/blob/696fdd193319cb1afa21e7b96d3b82dbaec566c8/contracts/ValidatorSetAuRa.sol#L164-L169

**Comment by akolotov** [comment]
Most of code has been covered by the comments during last year of development.
