### ISSUE TITLE
checks in setMinPerTx and setMaxPerTx inconsistent with initialization checks

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge-contracts#322]
As part of a new security audit it was found that checks used in `setMinPerTx` and `setMaxPerTx` are different from the checks used during intialization procedure.

For example,

https://github.com/poanetwork/tokenbridge-contracts/blob/20d262702defd3aed39870f3379f1cf0c314305e/contracts/upgradeable_contracts/BasicTokenBridge.sol#L92-L100

and 

https://github.com/poanetwork/tokenbridge-contracts/blob/20d262702defd3aed39870f3379f1cf0c314305e/contracts/upgradeable_contracts/erc20_to_native/HomeBridgeErcToNative.sol#L135-L139

as it is presented above `setMaxPerTx` checks that the new value is less than `dailyLimit`, `setMinPerTx` checks that the new value is less than `maxPerTx`. At the same time the initialization sequence additionally ensures that `maxPerTx` value is greater than `minPerTx` and `minPerTx` is greater than `0`.

Consider to change `setMaxPerTx` and `setMinPerTx` to have checks consistent with the initialization sequence. 

`setMaxPerTx` should also allow to set the value to `0` in order to have two ways to stop the bridge operations by both `setDailyLimit` and `swtMaxPerTx` (it will be used later in the _Relative Daily Limit_ feature.)

**Comment by k1rill-fedoseev** [comment]
If `setMaxPerTx` or `setDailyLimit` accepts `0` as an argument, then what should `setMinPerTx` do in case of `0` in `maxPerTx` or `dailyLimit`?
In other words, can we change min limit when the bridge is stopped?

**Comment by akolotov** [comment]
No, we do not update other limits if one of them is changed. It is due to desire to avoid implicit/indirect changes of bridge parameters.
