### ISSUE TITLE
Update the documentation with number of maximum validators

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge-contracts#326]
There are few places in the code where the list of validators is iterated:

https://github.com/poanetwork/tokenbridge-contracts/blob/20d262702defd3aed39870f3379f1cf0c314305e/contracts/upgradeable_contracts/BaseBridgeValidators.sol#L58-L76

and 

https://github.com/poanetwork/tokenbridge-contracts/blob/fdaab2777efe2f48c20a690c9f59196fa89e3631/contracts/upgradeable_contracts/ValidatorsFeeManager.sol#L23-L54

in these methods excessive number of validators could lead to "out of gas" issue.

Consider to do the following:
* perform a research and update the documentation with maximum number of validators which will not lead to the transaction interruption;
* update `setValidatorCount` to limit the number of bridge validator that can be added;
* update tests that will confirm that the number of invocations of `_addValidator` that corresponds to the recommended maximum of validators does not exceed some default gas limit (e.g. gas limit for the Ethereum Mainnet)
* update tests for the `initialize` methods in both `RewardableValidators` and `BridgeValidators` that will confirm that passing the validators list with size corresponding to the recommended maximum of validators does not exceed the default gas limit.

**Comment by k1rill-fedoseev** [comment]
I performed some kind of a research. I have tested contracts in Istanbul and Petersburg environments, considering `8000000` as a gas limit for a transaction.

I have came up with the following upper bounds for following contracts:
- BridgeValidators
  - `287` validators in Istanbul
  - `300` validators in Petersburg
- RewardableValidators
  - `156` validators in Istanbul
  - `161` validators in Petersburg
- Erc to Native home bridge
  - `154` validators in Istanbul (bounded by `executeAffirmation` call)
  - `140` validators in Petersburg (bounded by `executeAffirmation` call)
- Erc to Erc home bridge and Native to Erc home/foreign bridge
  - Calls involving fees distribution require less gas then `initialise` call, so upper bound on validators is `156`

**Comment by akolotov** [comment]
Great! So, let's have a limit in 50 validators.
