### ISSUE TITLE
Publish flattened sources automatically together with a new release tag

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge-contracts#351]
Consider to make a research and find if it is possible to publish flattened sources in the **Assets** section automatically when a new release is tagged.

![image](https://user-images.githubusercontent.com/20793260/71599611-fed02800-2b64-11ea-9f33-a3ddf55ef7ce.png)

Implement this functionality if such operation is achievable.

**Comment by k1rill-fedoseev** [comment]
Closed with #481
