### ISSUE TITLE
Incorrect AMB minimum gas usage estimation after EIP-2028

### ISSUE THREAD

**Issue by k1rill-fedoseev** [poanetwork/tokenbridge-contracts#352]
The [EIP-2028](https://eips.ethereum.org/EIPS/eip-2028) reduces the cost of calldata from `68` to `16` gas per non-zero byte.
In `MessageDelivery` contract we have the following:
https://github.com/poanetwork/tokenbridge-contracts/blob/c85aeb737bfd684b20b99520bd632ba4b8866583/contracts/upgradeable_contracts/arbitrary_message/MessageDelivery.sol#L14-L18
Should we reduce a multiplier to `16`?

**Comment by akolotov** [comment]
@k1rill-fedoseev good catch! Let's create a PR for this.

**Comment by akolotov** [comment]
I have also created https://github.com/poanetwork/tokenbridge-contracts/issues/354 to re-examine the way to send signatures.
