### ISSUE TITLE
Custom bridged token for the multi-token mediator

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge-contracts#559]
Currently the multi-token mediator calls the token fabric to deploy a new token every time when a new token is bridged from the Ethereum Mainnet. So, every bridged token has the same code base. But there is a request from the applications to have their own implementation of the bridge tokens. 

Consider to extend the multi-token AMB extension functionality as so it allows to configure an address of the contract that will be considered as the bridged token as soon as the request to deploy a reflection of some specific token from another side of the bridge appears. Such configuration must be possible only if the originating token was not yet bridged through the multi-token extension. As part of the configuration consider to check that the mediator is able to mint tokens on this contract and burn it in case of the success. Also, it makes sense to implement decimals shift functionality for the case when decimals of the originating token and its reflection are different.

**Comment by d10r** [comment]
fyi: I implemented something similar for the `amb_native_to_erc20` extension: https://github.com/d10r/tokenbridge-contracts/commit/f1e6e72f14be6bd879ac94150acaf1a8d5b45937

**Comment by akolotov** [comment]
Addressed here: https://github.com/poanetwork/omnibridge/pull/3
