### ISSUE TITLE
Home to Foreign Flow Question

### ISSUE THREAD

**Issue by ppoliani** [poanetwork/tokenbridge-contracts#563]
Hit there, 

I found this project extremely interesting and the code well written. Digging a little bit into the code I came across a question which I couldn't find an answer in the documentation. Basically, the question is regarding the Home -> Foreign flow. 

More specifically it is about the `executeAffirmation` on the Home bridge versus the `executeSignatures`. In the Foreign -> Home flow the request is as follows (according to the docs)

```
ERC677BridgeToken::transferAndCall
..ERC677BridgeToken::_superTransfer
....ERC20::transfer
......ERC20::_transfer
........emit Transfer
..emit Transfer
..ERC677BridgeToken::_contractFallback
>>Mediator
....BasicAMBErc677ToErc677::onTokenTransfer
......ForeignStakeTokenMediator::bridgeSpecificActionsOnTokenTransfer
........TokenBridgeMediator::passMessage
..........TokenBridgeMediator::setMessageHashValue
..........TokenBridgeMediator::setMessageHashRecipient
>>Bridge
..........MessageDelivery::requireToPassMessage
............ForeignAMB::emitEventOnMessageRequest
..............emit UserRequestForAffirmation
```

It is quite clear. In essence, the validator simply listens to the `UserRequestForAffirmation` events do some checks and then call `executeAffirmation` on the Home bridge. The result is that when enough validators have called that function on the HomeAMB it will process the encoded message i.e. call the `handledBridgeTokens` which will result in new tokens minted and transferred to the recipient address.

When going the other way Home -> Foreign the request is as follows:

```
>>Token
ERC677BridgeToken::transferAndCall
..ERC677BridgeToken::superTransfer
....BasicToken::transfer
......emit Transfer
..emit Transfer
..ERC677BridgeToken::contractFallback
>>Mediator
....BasicAMBErc677ToErc677::onTokenTransfer
......HomeStakeTokenMediator::bridgeSpecificActionsOnTokenTransfer
>>Token
........BurnableToken::burn
..........BurnableToken::_burn
>>Mediator
........TokenBridgeMediator::passMessage
..........TokenBridgeMediator::setMessageHashValue
..........TokenBridgeMediator::setMessageHashRecipient
>>Bridge
..........MessageDelivery::requireToPassMessage
............ForeignAMB::emitEventOnMessageRequest
..............emit UserRequestForSignature
>>BlockReward
........HomeStakeTokenFeeManager::_distributeFee
..........BlockRewardAuRaTokens::addBridgeTokenRewardReceivers
```

I looked into the validator code and it looks like we're listening to `UserRequestForSignature` and then call `submitSignature` on the HomeAmb bridge. When enough validators call this function it will emit `CollectedSignatures`. Again there is some additional logic on the validators side which will ultimately call `executeSignatures`.

My question is why is there an asymmetry of the steps for the two use cases Foreign -> Home and Home -> Foreign. 

More specifically, why do we need the `submitSignature` and then `executeSignatures` steps instead of something similar to the `executeAffirmation` on the Foreign -> Home scenario?

Pardon my ignorance, but I'm very interested in understanding the logic behind that.

**Comment by akolotov** [comment]
@ppoliani Thanks for your question!

Actually the answer consist of two parts:

1. Since it is assumed that the Foreign chain in most cases is the Ethereum Mainnet which is quite expensive, it is cheaper to send one transaction with collected confirmations instead of the several transactions per confirmation.

2. If you pay more attention on the `executeSignatures` method you will see that there is no restriction on who will send the confirmations: it could be any account not only one from the validators list. So, we can disable the watcher which looks for the `CollectedSignatures` events on the bridge oracles at all. Instead, users must be able to submit the signatures to the bridge contracts by themselves. Firstly, the user in case don't need to rely on the oracles if they re-send the confirmations. Second, the validators don't need to pay for the users' requests at all.

**Comment by ppoliani** [comment]
@akolotov Oh I see what's happening there. So that's why the `submitSignature` is processed on the Home chain. That makes absolute sense now. That's quite smart indeed. I didn't think about the gas related rationale. Cheers for the quick response. 

Is there any medium you guys use to discuss tech related stuff. You've got some nice projects and I'm sure there are other people that would be interested in understanding how it works. I know that Github issues is not probably the best way to raise similar questions.

**Comment by akolotov** [comment]
> Is there any medium you guys use to discuss tech related stuff.

You can consider to ask your questions here: https://discord.gg/mPJ9zkq
