### ISSUE TITLE
Remove `multi_amb_erc20_to_erc677` contracts

### ISSUE THREAD

**Issue by akolotov** [poanetwork/tokenbridge-contracts#591]
The contracts for the AMB OmniBridge extension are now in the separate repo: https://github.com/poanetwork/omnibridge. Consider to remove the contract related to `multi_amb_erc20_to_erc677` functionality from the tokenbridge contracts. It will reduce size of the repo and time of the compilation and testing.

**Comment by k1rill-fedoseev** [comment]
I think we can safely remove these contracts after upgrading ETH-xDAI Omnibridge to the latest version of the code from the new repo.
