### ISSUE TITLE
_isDestinationChainIdValid using sourceChainId() instead of destinationChainId()

### ISSUE THREAD

**Issue by RoyLai-InfoCorp** [poanetwork/tokenbridge-contracts#612]
https://github.com/poanetwork/tokenbridge-contracts/blob/master/contracts/upgradeable_contracts/arbitrary_message/BasicAMB.sol#L182-L184

This check for validDestinationChainId is comparing chainId with sourceChainId() instead of destinationChainId(). Is there a reason to it?

**Comment by k1rill-fedoseev** [comment]
Sorry for late response. Yes, this piece of code is correct.
The reason is that we are checking destination chain id of the incoming message on the recipient side. For all valid messages, it should be equal to the source chain id of the receiver contract.
